// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spxixwrieygayqqhulwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNweGl4d3JpZXlnYXlxcWh1bHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDY3ODMsImV4cCI6MjA5MDYyMjc4M30.yKsPkNwXY_eaGziXfIxPeNMxfIFaCE41MD4TybRlixA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});